### ISSUE TITLE
getPythonVersion breaks if $Env:PYTHONHOME exists

### ISSUE THREAD

**Issue by travisclagrone** [DavidWhittingham/ps-EnablePython#1]
If `$Env:PYTHONHOME` exists, then the private function `getPythonVersion` breaks for python versions other than the one referenced by `$Env:PYTHONHOME`.

### Given

```none
PS> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Microsoft Windows 10.0.17763 
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS> Test-Path -LiteralPath "$Env:HOME\AppData\Local\Programs\Python"
False

PS> $null -ne (Get-Command -Name 'python' -ErrorAction Ignore)
False

PS> $null -ne (Get-Module -Name 'EnablePython' -ListAvailable -ErrorAction Ignore)
False
```

### When

```powershell
$module = @{
    Name            = 'EnablePython'
    RequiredVersion = '2.0.1'
    Scope           = 'CurrentUser'
    AllowClobber    = $true
    AcceptLicense   = $true
}
Install-Module @module

$uriTemplate   = 'https://www.python.org/ftp/python/{0}/python-{0}.exe'
$installerFile = "$Env:HOME\Downloads\install-python.exe"
$versions      = @(
    '3.7.3'
    '3.6.8'
    '3.5.4'
)

foreach ($version in $versions) {

    $webRequest = @{
        Uri     = $uriTemplate -f $version
        OutFile = $installerFile
    }
    Invoke-WebRequest @webRequest

    # Defaults for unspecified options are documented at https://docs.python.org/3/using/windows.html#installing-without-ui
    $pythonInstallation = @(
        '/quiet'
        'AssociateFiles=0'
        'Shortcuts=0'
        'Include_launcher=0'
        'InstallLauncherAllUsers=0'
    )
    & $installerFile @pythonInstallation

    Remove-Item -LiteralPath $installerFile
}

$Env:PYTHONHOME = "$Env:HOME\AppData\Local\Programs\Python\Python37"

Import-Module 'EnablePython'

Get-Python
```

### Expected behavior

```none
Name     : Python Software Foundation Python 3.7 (64-bit) (x86-64)
Company  : PythonCore
Tag      : 3.7
Version  : 3.7.3
Platform : 64
Scope    : CurrentUser

Name     : Python Software Foundation 3.5 (x86-64)
Company  : PythonCore
Tag      : 3.5
Version  : 3.5.4
Platform : 64
Scope    : CurrentUser

Name     : Python Software Foundation Python 3.6 (64-bit) (x86-64)
Company  : PythonCore
Tag      : 3.6
Version  : 3.6.8
Platform : 64
Scope    : CurrentUser
```

### Actual behavior

```none
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\io.py", line 52, in <module>
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\abc.py", line 147
    print(f"Class: {cls.__module__}.{cls.__qualname__}", file=file)
                                                      ^
SyntaxError: invalid syntax
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Users\Travis.C.LaGrone\AppData\Local\Programs\Python\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'

Name     : Python Software Foundation Python 3.7 (64-bit) (x86-64)
Company  : PythonCore
Tag      : 3.7
Version  : 3.7.3
Platform : 64
Scope    : CurrentUser

Name     : Python Software Foundation 3.5 (x86-64)
Company  : PythonCore
Tag      : 3.5
Version  :
Platform : 64
Scope    : CurrentUser

Name     : Python Software Foundation Python 3.6 (64-bit) (x86-64)
Company  : PythonCore
Tag      : 3.6
Version  :
Platform : 64
Scope    : CurrentUser
```

**Comment by DavidWhittingham** [comment]
Thanks for logging the issue, I'll implement a fix and get a new release out.

**Comment by DavidWhittingham** [comment]
@travis-c-lagrone  This has been fixed, a new release will be up in a few minutes.
